apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-mongo
  labels:
    app: flask
spec:
  selector:
    app: flask
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
