apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: flask-mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
  type: ClusterIP
